apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
      - name: agent-container
        image: apache/skywalking-java-agent:9.3.0-java17
        volumeMounts:
          - name: skywalking-agent
            mountPath: /shared/agent
        command: [ "/bin/sh" ]
        args: [ "-c", "cp -R /skywalking/agent/* /shared/agent/" ]
      containers:
        - name: worker
          image: sivacit/voting-app-worker:latest
          env:
            - name: SPRING_APPLICATION_NAME
              value: worker-app
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/skywalking/agent/skywalking-agent.jar -Dskywalking.agent.service_name=worker -Dskywalking.collector.backend_service=dev.nuaura.ai:11800"
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking/agent
      volumes:
        - name: skywalking-agent
          emptyDir: {}
